feat(lsp-types): allow use of proposed spec types
ebkalderon/tower-lsp pull request #330
Opened 2022-03-21 19:11 UTC by sno2

Towards #329

2022-03-27 23:03 UTC, ebkalderon requested changes
This looks terrific! Thanks so much for the pull request. I agree with the described stability policy for the `proposed` feature. Just left one small piece of feedback for review before merging.

2022-03-27 23:03 UTC, ebkalderon commented on examples/custom_notification.rs
> +            offset_encoding: None,
I'm fairly sure this type implements `Default`. Any possibility we could replace these `#[cfg]` annotated fields with a `..Default::default()` initializer at the bottom instead?

2022-03-27 23:41 UTC, sno2 commented
I've fixed the issue and hopefully I won't get another formatting error as I ran `cargo fmt` before pushing.

2022-03-28 02:17 UTC, ebkalderon approved these changes
Awesome, thanks so much for addressing the feedback quickly! I think this is good to merge. :rocket:

2022-03-28 18:45 UTC, ebkalderon commented
Looks like two cases of `..Default::default()` in `examples/tcp.rs` are deemed unnecessary by Clippy, which is why CI is failing.

2022-03-28 19:53 UTC, sno2 commented
> Looks like two cases of `..Default::default()` in `examples/tcp.rs` are deemed unnecessary by Clippy, which is why CI is failing.

I think that clippy isn't being run with the `proposed` flag which is why clippy is giving an error.

2022-04-04 01:27 UTC, merged

2022-04-04 01:27 UTC, silvanshade commented
Going to merge this since it seems the feedback was addressed and the clippy issue was fixed. Thanks for the PR!

2022-04-05 01:19 UTC, sno2 commented
@silvanshade Hey, thanks for pulling my changes. Do you know if you could push a version bump for this integration or a rough time when the next release will be if there's a loose schedule?

2022-04-05 01:29 UTC, silvanshade commented
@sno2 I don't think I have the ability to publish a new version of the crate. @ebkalderon any thoughts on making a new release for this feature?

2022-04-15 17:58 UTC, ebkalderon commented
Sure, I'm publishing the release right now! Sorry for the delay. Will reply here again once it's on Crates.io.

2022-04-15 18:21 UTC, ebkalderon commented
Release [v0.17.0](https://github.com/ebkalderon/tower-lsp/releases/tag/v0.17.0) is now out on both GitHub and Crates.io! :tada: